"""
Django settings for myproject project.
Generated by 'django-admin startproject' using Django 6.0.1.
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- CẤU HÌNH GDAL/GEOS LINH HOẠT CHO WINDOWS ---
# 1. Thử tìm trong môi trường ảo (venv) trước - Ưu tiên máy của bạn hiện tại
VENV_OSGEO = os.path.join(BASE_DIR, 'venv', 'Lib', 'site-packages', 'osgeo')

if os.path.exists(VENV_OSGEO):
    # Thêm thư mục osgeo vào PATH hệ thống
    os.environ['PATH'] = VENV_OSGEO + os.pathsep + os.environ['PATH']
    
    # Hỗ trợ Python 3.13 load DLL (Bắt buộc cho Windows)
    if hasattr(os, 'add_dll_directory'):
        os.add_dll_directory(VENV_OSGEO)

    # Khai báo đường dẫn thư viện (Dùng tên gdal.dll thực tế trong venv)
    GDAL_LIBRARY_PATH = os.path.join(VENV_OSGEO, 'gdal.dll')
    GEOS_LIBRARY_PATH = os.path.join(VENV_OSGEO, 'geos_c.dll')
else:
    # 2. Nếu không có venv (máy người khác tải về), dùng đường dẫn mặc định OSGeo4W
    os.environ['GDAL_LIBRARY_PATH'] = r'C:\OSGeo4W\bin\gdal311.dll'
    os.environ['GEOS_LIBRARY_PATH'] = r'C:\OSGeo4W\bin\geos_c.dll'
# ------------------------------------------------

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(=1t+#m()*i*-_3*q%te$x6#fn-v+@gfm)p#&9=n8+!o0)pr71'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'main',
    'ckeditor',
    'ckeditor_uploader',
    'django.contrib.gis',
]

CKEDITOR_UPLOAD_PATH = "uploads/ckeditor/"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',          # Thư mục templates tổng của project
            BASE_DIR / 'main' / 'templates', # Thư mục templates riêng của app main
        ], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'main.context_processors.global_yoga_classes',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'yoga_db',
        'USER': 'postgres',
        'PASSWORD': '240505',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/
LANGUAGE_CODE = 'vi-vn'
TIME_ZONE = 'Asia/Ho_Chi_Minh'
USE_I18N = True
USE_L10N = False
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static", 
    BASE_DIR / "main" / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Cấu hình mặc định cho các trường ID tự động
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CKEDITOR_IMAGE_BACKEND = "pillow"