# Generated by Django 6.0.3 on 2026-03-10 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_branch_options_branch_image_branch_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(2, 'Thứ 2'), (3, 'Thứ 3'), (4, 'Thứ 4'), (5, 'Thứ 5'), (6, 'Thứ 6'), (7, 'Thứ 7'), (8, 'Chủ Nhật')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('yoga_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='main.yogaclass')),
            ],
            options={
                'verbose_name': 'Lịch học',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
    ]
