# Generated by Django 6.0.3 on 2026-03-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_classschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yogaclass',
            name='price',
            field=models.IntegerField(verbose_name='Học phí (VNĐ)'),
        ),
    ]
