# Generated by Django 6.0.3 on 2026-03-11 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_yogaclass_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booking_date'], 'verbose_name': 'Đơn đăng ký', 'verbose_name_plural': 'Các đơn đăng ký'},
        ),
        migrations.AddField(
            model_name='booking',
            name='full_name',
            field=models.CharField(default='Khách vãng lai', max_length=200, verbose_name='Họ tên khách hàng'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú admin'),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(default='0000000000', max_length=20, verbose_name='Số điện thoại'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ tư vấn'), ('contacted', 'Đã liên hệ'), ('confirmed', 'Thành công'), ('cancelled', 'Đã hủy')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
