# Generated by Django 6.0.3 on 2026-03-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Họ tên')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('message', models.TextField(verbose_name='Nội dung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày gửi')),
                ('is_read', models.BooleanField(default=False, verbose_name='Đã đọc')),
            ],
            options={
                'verbose_name': 'Tin nhắn liên hệ',
                'verbose_name_plural': 'Tin nhắn khách hàng',
                'ordering': ['-created_at'],
            },
        ),
    ]
