# Generated by Django 6.0.3 on 2026-03-31 10:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Nội dung bài viết'),
        ),
        migrations.AlterField(
            model_name='yogaclass',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Mô tả chi tiết'),
        ),
    ]
