# Generated by Django 6.0.3 on 2026-04-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_blogpost_content_alter_yogaclass_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Họ tên')),
                ('title', models.CharField(max_length=200, verbose_name='Chức vụ/Danh hiệu')),
                ('experience', models.CharField(max_length=100, verbose_name='Kinh nghiệm')),
                ('specialty', models.CharField(max_length=200, verbose_name='Chuyên môn chính')),
                ('image', models.ImageField(upload_to='teacher_images/', verbose_name='Ảnh đại diện')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
            ],
            options={
                'verbose_name': 'Giáo viên',
                'verbose_name_plural': 'Đội ngũ giáo viên',
                'ordering': ['order', 'id'],
            },
        ),
    ]
