# Generated by Django 6.0.3 on 2026-04-07 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='yogaclass',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yoga_classes', to='main.teacher', verbose_name='Huấn luyện viên'),
        ),
    ]
