# Generated by Django 6.0.3 on 2026-04-07 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_yogaclass_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='main.branch', verbose_name='Chi nhánh'),
        ),
    ]
