# Generated by Django 6.0.3 on 2026-04-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_teacher_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='working_branches',
            field=models.ManyToManyField(blank=True, related_name='working_teachers', to='main.branch', verbose_name='Các chi nhánh làm việc'),
        ),
    ]
