# Generated by Django 6.0.3 on 2026-04-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_teacher_working_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='session',
            field=models.TextField(blank=True, null=True, verbose_name='Khung giờ chọn'),
        ),
    ]
