# Generated by Django 6.0.3 on 2026-04-09 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_branch_is_active_branch_opening_hours_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchreview',
            options={'verbose_name': 'Đánh giá chi nhánh', 'verbose_name_plural': 'Các đánh giá chi nhánh'},
        ),
        migrations.RemoveField(
            model_name='branchreview',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='branchreview',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.branch', verbose_name='Chi nhánh'),
        ),
        migrations.AlterField(
            model_name='branchreview',
            name='comment',
            field=models.TextField(verbose_name='Bình luận'),
        ),
        migrations.AlterField(
            model_name='branchreview',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày đánh giá'),
        ),
        migrations.AlterField(
            model_name='branchreview',
            name='rating',
            field=models.IntegerField(default=5, verbose_name='Số sao (1-5)'),
        ),
        migrations.AlterField(
            model_name='branchreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người đánh giá'),
        ),
    ]
