# Generated by Django 6.0.3 on 2026-04-09 08:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_branchreview_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchreview',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='branchreview',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='branchreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AlterField(
            model_name='branchreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='branchreview',
            name='rating',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Số sao (1-5)'),
        ),
    ]
