# Generated by Django 6.0.3 on 2026-04-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_branchreview_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Cho phép hiển thị'),
        ),
    ]
