# Generated by Django 6.0.3 on 2026-05-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_add_is_replied_to_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày phản hồi'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='reply_content',
            field=models.TextField(blank=True, null=True, verbose_name='Nội dung phản hồi'),
        ),
    ]
